### ISSUE TITLE
@example support

### ISSUE THREAD

**Issue by kv-bpatram** [mr-doc/mr-doc#105]
Show code samples from [@example](http://usejsdoc.org/tags-example.html) tags in JSDoc blocks

**Comment by iwatakeshi** [comment]
Hey :), thanks for the feedback. The example tag should be supported...at least [in the source code](https://github.com/mr-doc/mr-doc/blob/master/lib/symbol.js)?

I unfortunately don't have time to look into it, however you can check the [default template](https://github.com/mr-doc/mr-doc-theme-default/tree/master/template) and the [cayman template](https://github.com/mr-doc/mr-doc-theme-cayman/blob/master/template/index.jade) and modify them so that the examples do appear. The templates should be about the same...they just have different styles. 

Once you find the culprit, go ahead and create a pull request and I'll merge it :)

**Comment by iwatakeshi** [comment]
Fixed in v3.1.5! Thanks!
