### ISSUE TITLE
Ability to specify individual source files for processing

### ISSUE THREAD

**Issue by xer0x** [mr-doc/mr-doc#116]
I've got a feature request for you. It may already be here. I am wondering if when processing a large project, is there a way to make `mr-doc` only update files that changed? It looks like the new vinyl-fs stuff might do this?

Great project, thanks.

**Comment by iwatakeshi** [comment]
@xer0x Thank you! It may be possible to add a watch capability. I'll consider it as I move forward.

**Comment by iwatakeshi** [comment]
@xer0x So, I did look into this issue and realized that there is a good news and bad news to this. The good news is that this will be possible with the output format being JSON because I can extend an existing file. The bad news is that this may not work for Markdown and HTML outputs because I need to update all the urls in html or the markdown file itself (if I decide to support markdown).

**Comment by xer0x** [comment]
@iwatakeshi thanks for looking into it. A little bad news is okay. I'm using HTML output right now. Someday I'll try out JSON when I try to get fancier.
